Nop.Plugin.Payments.PayU/Controllers/PaymentPayUController.cs
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Nop.Core;
using Nop.Plugin.Payments.PayU.Models;
using Nop.Plugin.Payments.PayU.Models.Notifications;
using Nop.Plugin.Payments.PayU.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.PayU.Controllers
{
    public class PaymentPayUController : BasePaymentController
    {
        private readonly ILogger _logger;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;
        private readonly ILocalizationService _localizationService;
        private readonly IPayUService _payUService;
        private readonly IStoreContext _storeContext;

        public PaymentPayUController(
            ILogger logger,
            IStoreService storeService,
            ISettingService settingService, 
            IPermissionService permissionService,
            ILocalizationService localizationService,
            IPayUService payUService,
            IWorkContext workContext,
            IStoreContext storeContext)
        {
            _logger = logger;
            _settingService = settingService;
            _permissionService = permissionService;
            _localizationService = localizationService;
            _payUService = payUService;
            _storeContext = storeContext;
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var payUPaymentSettings = _settingService.LoadSetting<PayUPaymentSettings>(storeScope);

            var model = new ConfigurationModel()
            {
                ActiveStoreScopeConfiguration = storeScope,
                UseSandbox = payUPaymentSettings.UseSandbox,
                SandboxClientId = payUPaymentSettings.SandboxClientId,
                SandboxClientSecret = payUPaymentSettings.SandboxClientSecret,
                ClientId = payUPaymentSettings.ClientId,
                ClientSecret = payUPaymentSettings.ClientSecret
            };

            return View("~/Plugins/Payments.PayU/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [AdminAntiForgery]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManagePaymentMethods))
            {
                return AccessDeniedView();
            }

            if (!ModelState.IsValid)
                return View("~/Plugins/Payments.PayU/Views/Configure.cshtml", model);

            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var payUPaymentSettings = _settingService.LoadSetting<PayUPaymentSettings>(storeScope);

            payUPaymentSettings.UseSandbox = model.UseSandbox;
            payUPaymentSettings.SandboxClientId = model.SandboxClientId;
            payUPaymentSettings.SandboxClientSecret = model.SandboxClientSecret;
            payUPaymentSettings.SandboxSecondKey = model.SandboxSecondKey;

            payUPaymentSettings.ClientId = model.ClientId;
            payUPaymentSettings.ClientSecret = model.ClientSecret;
            payUPaymentSettings.SecondKey = model.SecondKey;

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.UseSandbox, model.UseSandboxOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.SandboxClientId, model.SandboxClientIdOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.SandboxClientSecret, model.SandboxClientSecretOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.SandboxSecondKey, model.SandboxSecondKeyOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.ClientId, model.ClientIdOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.ClientSecret, model.ClientSecretOverrideForStore, storeScope, false);

            _settingService.SaveSettingOverridablePerStore(payUPaymentSettings,
                x => x.SecondKey, model.SecondKeyOverrideForStore, storeScope, false);

            _settingService.ClearCache();

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return View("~/Plugins/Payments.PayU/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Notify()
        {
            string body;
            using (var reader = new StreamReader(Request.Body, Encoding.UTF8))
            {
                body = await reader.ReadToEndAsync();
            }

            var verifySignature = _payUService.VerifySignature(body);

            if (!verifySignature)
            {
                _logger.Error($"PayU signature error. Body {body}. OpenPayU-Signature: {Request.Headers["OpenPayu-Signature"]}");
                return Ok();
            }

            var isRefundNotification = JObject.Parse(body)["refund"];
            if (isRefundNotification !=  null)
            {
                var refundNotification = Newtonsoft.Json.JsonConvert.DeserializeObject<NotificationRefund>(body);
                _logger.Information($"Refund notification, order extId: {refundNotification?.ExtOrderId}, order status: {refundNotification?.Refund?.Status}");

                return Ok();
            }

            var notification = Newtonsoft.Json.JsonConvert.DeserializeObject<Notification>(body);
            _logger.Information($"Notification, order extId: {notification?.Order?.ExtOrderId}, order status: {notification?.Order?.Status}");
            _payUService.Notify(notification);

            return Ok();
        }

        public IActionResult ProcessingPayment(int orderId)
        {
            return RedirectToRoute("CheckoutCompleted", new { orderId });
        }
    }
}

Nop.Plugin.Payments.PayU/Views/Configure.cshtml
@model Nop.Plugin.Payments.PayU.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentPayU" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandboxOverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SandboxClientIdOverrideForStore" asp-input="SandboxClientId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SandboxClientId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SandboxClientId" />
                        <span asp-validation-for="SandboxClientId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SandboxClientSecretOverrideForStore" asp-input="SandboxClientSecret" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SandboxClientSecret" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SandboxClientSecret" />
                        <span asp-validation-for="SandboxClientSecret"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SandboxSecondKeyOverrideForStore" asp-input="SandboxSecondKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SandboxSecondKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SandboxSecondKey" />
                        <span asp-validation-for="SandboxSecondKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ClientIdOverrideForStore" asp-input="ClientId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ClientId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ClientId" />
                        <span asp-validation-for="ClientId"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ClientSecretOverrideForStore" asp-input="ClientSecret" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ClientSecret" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ClientSecret" />
                        <span asp-validation-for="ClientSecret"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="SecondKeyOverrideForStore" asp-input="SecondKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="SecondKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="SecondKey" />
                        <span asp-validation-for="SecondKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Payments.PayU/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.PayU.PaymentInfo")</b></p>
        </td>
    </tr>
</table>